# Generated by Django 3.2.4 on 2021-08-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210802_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userarticle',
            name='article',
        ),
        migrations.AddField(
            model_name='userarticle',
            name='url',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
